# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: 2503
          POSTGRES_USER: postgres
          POSTGRES_DB: new_relic
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Java Spring Project
        run: mvn clean install -DskipTests

      - name: Run Spring Boot app with New Relic
        run: java  -jar target/lab1-0.0.1-SNAPSHOT.jar &

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run local K6 test
        uses: grafana/run-k6-action@v1
        with:
          path: k6_test/test.js



      #    steps:
#    - uses: actions/checkout@v4
#      with:
#        fetch-depth: 0
#    - name: Set up JDK 21
#      uses: actions/setup-java@v4
#      with:
#        java-version: '21'
#        distribution: 'temurin'
#        cache: maven

#    - name: Build with Maven
#      run: mvn clean install

#- name: SonarCloud Scan
#      uses: sonarsource/sonarcloud-github-action@master
 #     env:
  #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #  with:
     #   args: >
      #    -Dsonar.organization=yuliapetryk
       #   -Dsonar.projectKey=yuliapetryk_Web-Systems-Lab1

 #   - name: Archive Artifacts
 #     uses: actions/upload-artifact@v4
 #     with:
 #       name: my-artifact
 #       path: target/*.jar

 #   - name: Upload Test Reports
 #     uses: actions/upload-artifact@v4
 #     with:
  #      name: test-reports
  #      path: target/surefire-reports/*.xml

